# Práctica 06

[![Abrir en Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/manuxch/calculo_avanzado/blob/main/06-normas_vectores_matrices/code/practica_06.ipynb)

## Ejercicio 1

La expresión general para las normas $p$ para vectores en $\mathbb{R}^n$ es:
$$\lVert \vec{x} \rVert = \left( \sum_{i=1}^n |x_i|^p \right)^{1/p} $$
En particular, las normas $l_1$, $l_2$ y $l_{\infty}$ son:
- $\lVert \vec{x} \rVert_1 = \sum_{i = 1}^n |x_i| $
- $\lVert \vec{x} \rVert_2 = \left( \sum_{i = 1}^n |x_i|^2 \right)^{1/2} $
- $\lVert \vec{x} \rVert_{\infty} = \max_{1 \leq i \leq n} |x_i| $

Para $\vec{x} = [3, -4, 0, 3/2]$ resultan:
- $l_1$:
  $$ \lVert \vec{x} \rVert_1 = |3| + |-4| + |0| + |3/2| = \frac{17}{2} $$
- $l_2$:
  $$ \lVert \vec{x} \rVert_2 = \sqrt{|3|^2 + |-4|^2 + |0|^2 + |3/2|^2} = \frac{\sqrt{109}}{2} $$
- $l_{\infty}$:
  $$ \lVert \vec{x} \rVert_{\infty} = \max\{|3|, |-4|, |0|, |3/2|\} = 4 $$

Para $\vec{x} = [2, 1, -3, 4]$ resultan:
- $l_1$:
  $$ \lVert \vec{x} \rVert_1 = |2| + |1| + |-3| + |4| = 10 $$
- $l_2$:
  $$ \lVert \vec{x} \rVert_2 = \sqrt{|2|^2 + |1|^2 + |-3|^2 + |4|^2} = \sqrt{30} $$
- $l_{\infty}$:
  $$ \lVert \vec{x} \rVert_{\infty} = \max\{|2|, |1|, |-3|, |4|\} = 4 $$

  Para $\vec{x} = [\sin k, \cos k, 2^k]$ resultan:
- $l_1$:
  $$ \lVert \vec{x} \rVert_1 = |\sin k| + |\cos k| + 2^k $$
- $l_2$:
  $$ \lVert \vec{x} \rVert_2 = \sqrt{|\sin k|^2 + |\cos k|^2 + |2^k|^2 } = \sqrt{1 + 4^k} $$
- $l_{\infty}$:
  $$ \lVert \vec{x} \rVert_{\infty} = \max\{|\sin k|, |\cos k|, |2^k|\} = 2^k $$

## Ejercicio 2

Para resolver este problema, y dado que implica realizar muchos cálculos en forma repetitiva, vamos a implementar funciones en Python que reciban como argumento la matriz cuya norma se quiere calcular.

In [1]:
import numpy as np

def frobenius(A):
    suma_elementos_cuadrados = np.sum(A**2)
    norma = np.sqrt(suma_elementos_cuadrados)
    return norma

def maxima(A):
    elemento_maximo = np.max(np.abs(A))
    return elemento_maximo

def norma_p1(A):
    suma_elementos = np.sum(np.abs(A))
    return suma_elementos

Ahora definimos las matrices de cada caso como arrays de numpy, y luego hacemos una lista con estas matrices:

In [2]:
A_a = np.array([[10, 15], [0, 1]])
A_b = np.array([[10, 0], [15, 1]])
A_c = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
A_d = np.array([[4, -1, 7], [-1, 4, 0], [-7, 0, 4]])

matrices = [A_a, A_b, A_c, A_d]

Finalmente, recorremos esta lista de matrices con un ``for`` de modo de pasar cada matriz como argumento de las funciones definidias previamente:

In [3]:
for matriz in matrices:
    print('Matriz:')
    print(matriz)
    print(f'Norma frobenius: {frobenius(matriz)}')
    print(f'Norma máxima: {maxima(matriz)}')
    print(f'Norma p1: {norma_p1(matriz)}')
    print(20 * '-')

Matriz:
[[10 15]
 [ 0  1]]
Norma frobenius: 18.05547008526779
Norma máxima: 15
Norma p1: 26
--------------------
Matriz:
[[10  0]
 [15  1]]
Norma frobenius: 18.05547008526779
Norma máxima: 15
Norma p1: 26
--------------------
Matriz:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
Norma frobenius: 4.0
Norma máxima: 2
Norma p1: 10
--------------------
Matriz:
[[ 4 -1  7]
 [-1  4  0]
 [-7  0  4]]
Norma frobenius: 12.165525060596439
Norma máxima: 7
Norma p1: 28
--------------------


## Ejercicio 3

Podemos mostrar que la norma $\lVert \cdot \rVert_{\text{máx}}$ no satisface la propiedad sub-multiplicativa utilizando para ello la matriz:
$$A = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} $$

Para esta matriz, la norma máxima es $\lVert A \rVert_{\text{máx}} = 1$. Por otra parte:
$$A \cdot A = \begin{bmatrix} 2 & 2 \\ 2 & 2 \end{bmatrix} $$
cuya norma máxima es $\lVert A\cdot A \rVert_{\text{máx}} = 2 $. De este modo, no se cumple la propiedad sub-multiplicativa:
$$\lVert A \cdot A \rVert_{\text{máx}} \leq \lVert A \rVert_{\text{máx}} \cdot \lVert A \rVert_{\text{máx}} $$ 
ya que 
$$2 > 1 \cdot 1 $$

## Ejercicio 4

Al igual que en el ejercicio 2, vamos a escribir funciones que reciban como argumento una matriz (como array de numpy) y devuelva las correspondientes normas inducidas:

In [4]:
def l1_inducida(A):
    suma_columna = np.sum(A, axis=0)
    norma = np.max(suma_columna)
    return norma

def linf_inducida(A):
    suma_fila = np.sum(A, axis=1)
    norma = np.max(suma_fila)
    return norma

In [5]:
for matriz in matrices:
    print('Matriz:')
    print(matriz)
    print(f'Norma inducida l1: {l1_inducida(matriz)}')
    print(f'Norma inducida máxima: {linf_inducida(matriz)}')
    print(20 * '-')

Matriz:
[[10 15]
 [ 0  1]]
Norma inducida l1: 16
Norma inducida máxima: 25
--------------------
Matriz:
[[10  0]
 [15  1]]
Norma inducida l1: 25
Norma inducida máxima: 16
--------------------
Matriz:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
Norma inducida l1: 1
Norma inducida máxima: 1
--------------------
Matriz:
[[ 4 -1  7]
 [-1  4  0]
 [-7  0  4]]
Norma inducida l1: 11
Norma inducida máxima: 10
--------------------
